// Code generated by "stringer -type=Cause"; DO NOT EDIT.

package asdu

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unused-0]
	_ = x[Periodic-1]
	_ = x[Background-2]
	_ = x[Spontaneous-3]
	_ = x[Initialized-4]
	_ = x[Request-5]
	_ = x[Activation-6]
	_ = x[ActivationCon-7]
	_ = x[Deactivation-8]
	_ = x[DeactivationCon-9]
	_ = x[ActivationTerm-10]
	_ = x[ReturnInfoRemote-11]
	_ = x[ReturnInfoLocal-12]
	_ = x[FileTransfer-13]
	_ = x[Authentication-14]
	_ = x[SessionKey-15]
	_ = x[UserRoleAndUpdateKey-16]
	_ = x[InterrogatedByStation-20]
	_ = x[InterrogatedByGroup1-21]
	_ = x[InterrogatedByGroup2-22]
	_ = x[InterrogatedByGroup3-23]
	_ = x[InterrogatedByGroup4-24]
	_ = x[InterrogatedByGroup5-25]
	_ = x[InterrogatedByGroup6-26]
	_ = x[InterrogatedByGroup7-27]
	_ = x[InterrogatedByGroup8-28]
	_ = x[InterrogatedByGroup9-29]
	_ = x[InterrogatedByGroup10-30]
	_ = x[InterrogatedByGroup11-31]
	_ = x[InterrogatedByGroup12-32]
	_ = x[InterrogatedByGroup13-33]
	_ = x[InterrogatedByGroup14-34]
	_ = x[InterrogatedByGroup15-35]
	_ = x[InterrogatedByGroup16-36]
	_ = x[RequestByGeneralCounter-37]
	_ = x[RequestByGroup1Counter-38]
	_ = x[RequestByGroup2Counter-39]
	_ = x[RequestByGroup3Counter-40]
	_ = x[RequestByGroup4Counter-41]
	_ = x[UnknownTypeID-44]
	_ = x[UnknownCOT-45]
	_ = x[UnknownCA-46]
	_ = x[UnknownIOA-47]
}

const (
	_Cause_name_0 = "UnusedPeriodicBackgroundSpontaneousInitializedRequestActivationActivationConDeactivationDeactivationConActivationTermReturnInfoRemoteReturnInfoLocalFileTransferAuthenticationSessionKeyUserRoleAndUpdateKey"
	_Cause_name_1 = "InterrogatedByStationInterrogatedByGroup1InterrogatedByGroup2InterrogatedByGroup3InterrogatedByGroup4InterrogatedByGroup5InterrogatedByGroup6InterrogatedByGroup7InterrogatedByGroup8InterrogatedByGroup9InterrogatedByGroup10InterrogatedByGroup11InterrogatedByGroup12InterrogatedByGroup13InterrogatedByGroup14InterrogatedByGroup15InterrogatedByGroup16RequestByGeneralCounterRequestByGroup1CounterRequestByGroup2CounterRequestByGroup3CounterRequestByGroup4Counter"
	_Cause_name_2 = "UnknownTypeIDUnknownCOTUnknownCAUnknownIOA"
)

var (
	_Cause_index_0 = [...]uint8{0, 6, 14, 24, 35, 46, 53, 63, 76, 88, 103, 117, 133, 148, 160, 174, 184, 204}
	_Cause_index_1 = [...]uint16{0, 21, 41, 61, 81, 101, 121, 141, 161, 181, 201, 222, 243, 264, 285, 306, 327, 348, 371, 393, 415, 437, 459}
	_Cause_index_2 = [...]uint8{0, 13, 23, 32, 42}
)

func (i Cause) String() string {
	switch {
	case i <= 16:
		return _Cause_name_0[_Cause_index_0[i]:_Cause_index_0[i+1]]
	case 20 <= i && i <= 41:
		i -= 20
		return _Cause_name_1[_Cause_index_1[i]:_Cause_index_1[i+1]]
	case 44 <= i && i <= 47:
		i -= 44
		return _Cause_name_2[_Cause_index_2[i]:_Cause_index_2[i+1]]
	default:
		return "Cause(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
